language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: wEJBOQZOn0Csrwu2KWo7ggZJ6aZPFWJ8NgF5v60+paWeG93Oq85u2x2HuxqqQuWJ+vWFBL+ox2jUxE2ufoKQog1Vu11IUJkJMpJosvHlgVYCky8MK8hjtN1TeVsI3lG5TSnexB3FJ7wrLHgNketg18uckQkLEI9AsrFYaIU8EsWuEGHrK3nFW1ilGVSpJut7nT48ZV0ATaV0qigsbTvU3VpyCThyflsKYME2FdeA/WW8c4M+QwcwWmlJiZdICqWlSAZo8LlJ7UB4OnXVtoYOxjSI/zOh2qXvo4yWuhEpc8ZUF2ft+9W4SRuLdG7N4Z0LjGnjgaU85Rp+nuWJpwkxd6xooNtExS3h89tB1h0L+jkL24O0Rb8x7SgwTimk1xEB2fkGX6rtboCfX2E2jX6hy/DgEhXPQa6c+Uu90C6A02NiqaKbcn+oSeBW1lkHAt5/Tv6xFp2MSAUbuwJXH1lsjXPYZfWVfClN7vXdUxkrsrs073DdjN5kOtevhxvcZH8ezd2F8ulw00xgsVw9R8NAVqMu9cQEmL8p1HHe0oCT0qC/3gRx28tvaLgl9kshuFOyOCYeGKAk4AioSDmOsaO6vEzn3jSWKB74ivRwx1ZUEUkw7Rc7hCVBn6Q/0L0gO0Vw99wER3FxyzFNxdw09ArYbJuldvCWAvf6j7xw0ibYkXI=
  app: afternoon-coast-84211
  on:
    repo: wangmeng255/mongo-contacts
